In [1]:
import pandas as pd
import numpy as np

In [44]:
#------------------
# LOAD THE DATASET
#------------------

data = pd.read_csv('lastfm.csv')

# Create a new dataframe without the user ids.
data_items = data.drop('user', 1)

In [53]:
data_items.loc[1:, 'yann tiersen':]*0
data_items['yann tiersen'].apply(lambda x: 0 if x==0 else 0, inplace=True)
data_items.loc[1:, 'yann tiersen':].head(30)

TypeError: <lambda>() got an unexpected keyword argument 'inplace'

In [43]:
#把其中一欄歌手值拿掉的做法
data_test = data_items.loc[:, 'yann tiersen':]
data_r = data_items.loc[1:, 'yann tiersen':].mul(0)
data_items = data_items.drop('yann tiersen',axis=1)
#這邊不能用concat 他會把df上下接在一起
pd.concat([data_items, data_r], ignore_index=True)

,a perfect circle,abba,ac/dc,adam green,aerosmith,afi,air,alanis morissette,alexisonfire,alicia keys,...,timbaland,tom waits,tool,tori amos,travis,trivium,u2,underoath,volbeat,yann tiersen
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2446,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2447,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2448,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2449,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2450,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [ ]:
#用numpy吧...不會寫numpy啦啦啦
data_items.loc[:, '':] = np.()

In [4]:
# As a first step we normalize the user vectors to unit vectors.

# magnitude = sqrt(x2 + y2 + z2 + ...)
magnitude = np.sqrt(np.square(data_items).sum(axis=1))

# unitvector = (x / magnitude, y / magnitude, z / magnitude, ...)
data_items = data_items.divide(magnitude, axis='index')

In [5]:
data_items.tail(5)

,a perfect circle,abba,ac/dc,adam green,aerosmith,afi,air,alanis morissette,alexisonfire,alicia keys,...,three days grace,timbaland,tom waits,tool,tori amos,travis,trivium,u2,underoath,volbeat
1221,0.0,0.0,0.235702,0.235702,0.235702,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1222,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.288675,0.0,0.0,0.0,0.0,0.0,0.0
1223,0.0,0.0,0.213201,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1224,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1225,0.0,0.0,0.000000,0.242536,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.242536,0.000000,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
#------------------
#SVD Decomposition
#------------------
#用scipy的svd function 可以自行選擇設定潛在因素(lantent factor U, sigma, VT)
#R=UΣVT  保留前k個最重要的因素
from scipy.sparse.linalg import svds
U, sigma, Vt = svds(data_items, k = 50)
# the Σ returned is just the values instead of a diagonal matrix
sigma = np.diag(sigma)
print(sigma)

[[2.50781821 0.         0.         ... 0.         0.         0.        ]
 [0.         2.52523314 0.         ... 0.         0.         0.        ]
 [0.         0.         2.53204612 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 4.96554595 0.         0.        ]
 [0.         0.         0.         ... 0.         5.9779571  0.        ]
 [0.         0.         0.         ... 0.         0.         8.70027265]]

In [7]:
#------------------
#Making Predictions from Decomposed Matrices 
#------------------+ magnitude.reshape(-1, 1)
all_user_predicted_ratings = np.dot(np.dot(U, sigma), Vt) 
preds_df = pd.DataFrame(all_user_predicted_ratings, columns = data_items.columns)

In [8]:
#------------------
#Making Singer Recommendations
#------------------
def recommend_singers(predictions_df, user):
    # Get and sort the user's predictions
    user_index = data[data.user == user].index.tolist()[0]
    sorted_user_predictions = predictions_df.iloc[user_index].sort_values(ascending=False)
    
    # Get the artists the user has likd.
    known_user_likes = data_items.iloc[user_index]
    known_user_likes = known_user_likes[known_user_likes >0].index.values
    
    # Drop & Print known_user_likes
    sorted_user_predictions = sorted_user_predictions.drop(known_user_likes)
    print(known_user_likes)
    return sorted_user_predictions

#mf_prediction = recommend_singers(preds_df, 5985)

print(preds_df)

#print(mf_prediction.head(20))

      a perfect circle      abba     ac/dc  adam green  aerosmith       afi  \
0             0.009529 -0.056191  0.043425   -0.028255   0.016646  0.012218
1            -0.011485 -0.019011  0.005005    0.038644   0.023587  0.011374
2            -0.008019  0.017128  0.024471    0.006060  -0.002737  0.021860
3             0.001003  0.057466 -0.036866    0.032746  -0.008103  0.004083
4            -0.002744  0.033118 -0.001003    0.030884   0.000749  0.008009
...                ...       ...       ...         ...        ...       ...
1221          0.008136  0.008535  0.184468    0.059525   0.044150  0.001733
1222          0.084120  0.008616 -0.006047    0.025925  -0.004194  0.013806
1223         -0.008438  0.041593  0.241622    0.008875   0.011904  0.009488
1224          0.010079  0.038148  0.018636    0.011061  -0.023410  0.029034
1225         -0.016411 -0.012046 -0.016666    0.089560   0.005862  0.011236

           air  alanis morissette  alexisonfire  alicia keys  ...  \
0    -0.020893           0.028510      0.009578     0.037742  ...
1     0.022277           0.022445     -0.003897     0.010830  ...
2     0.005247           0.017673     -0.006034    -0.005516  ...
3    -0.030059          -0.009161      0.014815    -0.012282  ...
4     0.031445          -0.011615      0.017626    -0.000273  ...
...        ...                ...           ...          ...  ...
1221  0.033374           0.003765     -0.009107     0.011389  ...
1222  0.014932           0.012704      0.002223    -0.016788  ...
1223 -0.004823          -0.002636      0.024383     0.015392  ...
1224 -0.020932          -0.010297      0.009378     0.002702  ...
1225  0.039639           0.001417     -0.008668     0.025447  ...

      three days grace  timbaland  tom waits      tool  tori amos    travis  \
0             0.011925   0.015333  -0.002502 -0.003849   0.005844  0.004017
1             0.062575  -0.027208   0.007631 -0.006330  -0.009545  0.012066
2             0.005250  -0.027633  -0.002309 -0.009199   0.041455  0.003163
3            -0.002696   0.020835  -0.003409  0.019959  -0.015222 -0.007221
4             0.006189   0.095147  -0.007545  0.023117  -0.010017 -0.007310
...                ...        ...        ...       ...        ...       ...
1221          0.002724  -0.004702   0.067681  0.012875  -0.013692  0.020439
1222         -0.010195   0.006836   0.020832  0.085459   0.043144  0.026099
1223         -0.006287   0.009220   0.007602 -0.004200   0.003804 -0.006438
1224          0.030883  -0.009474   0.021949  0.042325   0.008316 -0.003018
1225         -0.012277   0.027229   0.077114 -0.022070   0.003913  0.029905

       trivium        u2  underoath   volbeat
0    -0.004668  0.015832  -0.004926 -0.011557
1    -0.020684  0.036651  -0.000175 -0.000782
2     0.028959  0.010011  -0.001462 -0.013839
3    -0.008235 -0.010059  -0.005627  0.017161
4    -0.002302 -0.009764   0.027780  0.015508
...        ...       ...        ...       ...
1221  0.016956  0.028983  -0.000802  0.025620
1222  0.018986 -0.000090  -0.002646  0.027763
1223  0.049005 -0.005364   0.010203  0.006415
1224  0.003188 -0.021782   0.011367 -0.011126
1225  0.009718  0.000854  -0.001550 -0.006669

[1226 rows x 284 columns]

In [9]:
#------------------
#Making evaluation by test-set
#------------------